---
title: "KFAS Cookbook 的なもの"
author: "tatamiya"
date: "2023-10-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(KFAS)
library(dplyr)
library(ggplot2)
library(gridExtra)
```

# 一般形

$$
\begin{aligned}
    \boldsymbol{y}_t &= \boldsymbol{Z}_t \boldsymbol{\alpha}_t + \boldsymbol{\boldsymbol{\varepsilon}}_t, \quad \boldsymbol{\varepsilon}_t \sim N(\boldsymbol{0}, \boldsymbol{H}_t)\\
    \boldsymbol{\alpha}_{t+1} &= \boldsymbol{T}_t \boldsymbol{\alpha}_t + \boldsymbol{R}_t \boldsymbol{\eta}_t, \quad \boldsymbol{\eta}_t \sim N(\boldsymbol{0}, \boldsymbol{Q}_t)
\end{aligned}
$$

# サンプルデータの準備

```{r}
set.seed(13)
x1 <- 100 + arima.sim(model=list(ar=0.999), n=100)

s <- 2.5 * sin(seq(0, 99, length.out=100) * 2 * pi / 4)
y <- 1.2 * x1 + s + rnorm(100)
y[71:100] <- y[71:100] + 10

time.points <- seq.Date(as.Date("2014-01-01"), by=1, length.out=100)
datetime_cp <- time.points[71]

data <- data.frame(day=time.points, y=y, x1=x1) %>%
  mutate(flg_interfere = case_when(day>=datetime_cp~1, .default = 0)) 

p1 <- ggplot(data=data) +
  geom_line(aes(x=day, y=y))

p2 <- ggplot(data=data) +
  geom_line(aes(x=day, y=x1))

grid.arrange(p1, p2)
```
```{r, include=FALSE}
makeDataFrameQuantile <- function(data, fitted_model, states="all", interval="prediction", n_ahead=5, level=0.95){
  
  alphahat <- predict(fitted_model, interval=interval, states=states, level=level)
  
  pred <- predict(fitted_model, interval=interval, states=states, n.ahead = n_ahead, level=level)
  
  date_estimated <- seq(
    from=data$day[1],
    by="days",
    len=length(data$day)+n_ahead)
  
  estimated <- data.frame(day = date_estimated,
                          pred = c(alphahat[, 1], pred[, 1]),
                          lwr = c(alphahat[, 2], pred[, 2]),
                          upr = c(alphahat[, 3], pred[, 3])
  )
  
  return(estimated)
}
```


# Local Level Model

$$
\begin{aligned}
y_t &= \mu_t + \varepsilon_t, \quad \varepsilon_t \sim N(0, \sigma_\varepsilon^2)\\
\mu_{t+1} &= \mu_t + \eta_t, \quad \eta_t \sim N(0, \sigma_\eta^2)
\end{aligned}
$$

```{r}
model_ll <- SSModel(y ~ SSMtrend(degree = 1, Q = NA),
                 data=data, H=NA)

fit_ll <- fitSSM(model_ll, numeric(2), method="BFGS")
```

## 全成分

$$
P(y_t \vert y_{1:T})
$$

```{r}
data_all_ll <- makeDataFrameQuantile(fitted_model = fit_ll$model, data=data, states = "all", interval = "prediction", n_ahead=10) %>%
  left_join(data, by="day")

p <- ggplot(data_all_ll) +
  geom_vline(xintercept = max(data$day), linetype="dotted")+
  geom_line(aes(x=day, y=y), color="black") + 
  geom_line(aes(x=day, y=pred), color="blue", linetype="dashed") + 
  geom_ribbon(aes(x = day, ymin = lwr, ymax = upr),
            fill = "blue", alpha = 0.5)
print(p)
```

## トレンド成分

$$
  P(\mu_t \vert y_{1:T})
$$

```{r}
data_trend_ll <- makeDataFrameQuantile(fitted_model = fit_ll$model,
                                     data=data,
                                     states = "trend",
                                     interval = "confidence",
                                     n_ahead=10
                                     ) %>%
  left_join(data, by="day")

p <- ggplot(data_trend_ll) +
  geom_vline(xintercept = max(data$day), linetype="dotted")+
  geom_line(aes(x=day, y=pred), color="blue", linetype="dashed") + 
  geom_ribbon(aes(x = day, ymin = lwr, ymax = upr),
            fill = "blue", alpha = 0.5)
print(p)
```

# 平滑化トレンドモデル

$$
\begin{aligned}
y_t &= \mu_t + \varepsilon_t, \quad \varepsilon_t \sim N(0, \sigma_\varepsilon^2)\\
\mu_{t+1} &= \mu_t + \delta_t\\
\delta_{t+1} &= \delta_t +  \zeta_t, \quad \zeta_t \sim N(0, \sigma_\zeta^2)
\end{aligned}
$$

$$
\begin{aligned}
y_t = (1, 0)
\begin{pmatrix}
\mu_t\\
\delta_t
\end{pmatrix}
+ \varepsilon_t, \quad \varepsilon_t \sim N(0, \sigma_\varepsilon^2)\\

\begin{pmatrix}
\mu_{t+1}\\
\delta_{t+1}
\end{pmatrix}
=
\begin{pmatrix}
1 & 1\\
0 & 1
\end{pmatrix}
\begin{pmatrix}
\mu_{t}\\
\delta_{t}
\end{pmatrix}
+ 
\begin{pmatrix}
1 & 0\\
0 & 1
\end{pmatrix}
\boldsymbol{\zeta}_t\\

\boldsymbol{\zeta}_t \sim N\left(
\begin{pmatrix}
0\\
0
\end{pmatrix},
\begin{pmatrix}
0 & 0\\
0 & \sigma_\zeta^2
\end{pmatrix}
\right)
\end{aligned}
$$

## モデリング

```{r}
model_st <- SSModel(y ~ SSMtrend(degree = 2, Q = c(list(0), list(NA))),
                 data=data, H=NA)

fit_st <- fitSSM(model_st, numeric(2), method="BFGS")
```


### モデルパラメータ

$$
\boldsymbol{Z} = (1,0)
$$

```{r}
model_st$Z
```

$$
\boldsymbol{T} =
\begin{pmatrix}
1 & 1\\
0 & 1
\end{pmatrix}
$$


```{r}
model_st$T
```

$$
\boldsymbol{R} = \begin{pmatrix}
1 & 0\\
0 & 1
\end{pmatrix}
$$


```{r}
model_st$R
```


### 推定パラメータ

$$
\boldsymbol{H}=\sigma_\varepsilon^2
$$

```{r}
fit_st$model$H
```


$$
\boldsymbol{Q} = 
\begin{pmatrix}
0 & 0\\
0 & \sigma_\zeta^2
\end{pmatrix}
$$
```{r}
fit_st$model$Q

```

## 結果

### 全成分

$$
P(y_t \vert y_{1:T})
$$

```{r}
data_all_st <- makeDataFrameQuantile(fitted_model = fit_st$model, data=data, states = "all", interval = "prediction", n_ahead=10) %>%
  left_join(data, by="day")

p <- ggplot(data_all_st) +
  geom_vline(xintercept = max(data$day), linetype="dotted")+
  geom_line(aes(x=day, y=y), color="black") + 
  geom_line(aes(x=day, y=pred), color="blue", linetype="dashed") + 
  geom_ribbon(aes(x = day, ymin = lwr, ymax = upr),
            fill = "blue", alpha = 0.5)
print(p)
```

### トレンド成分

$$
  P(\mu_t \vert y_{1:T})
$$

```{r}
data_trend_st <- makeDataFrameQuantile(fitted_model = fit_st$model,
                                     data=data,
                                     states = "trend",
                                     interval = "confidence",
                                     n_ahead=10
                                     ) %>%
  left_join(data, by="day")

p <- ggplot(data_trend_st) +
  geom_vline(xintercept = max(data$day), linetype="dotted")+
  geom_line(aes(x=day, y=pred), color="blue", linetype="dashed") + 
  geom_ribbon(aes(x = day, ymin = lwr, ymax = upr),
            fill = "blue", alpha = 0.5)
print(p)
```

### 傾き成分

$$
  P(\delta_t \vert y_{1:T})
$$

```{r}
data_slope_st <- makeDataFrameQuantile(fitted_model = fit_st$model,
                                     data=data,
                                     states = "slope",
                                     interval = "confidence",
                                     n_ahead=10
                                     ) %>%
  left_join(data, by="day")

p <- ggplot(data_slope_st) +
  geom_vline(xintercept = max(data$day), linetype="dotted")+
  geom_line(aes(x=day, y=pred), color="blue", linetype="dashed") + 
  geom_ribbon(aes(x = day, ymin = lwr, ymax = upr),
            fill = "blue", alpha = 0.5)
print(p)
```


# ローカル線形トレンドモデル

$$
\begin{aligned}
y_t &= \mu_t + \varepsilon_t, \quad \varepsilon_t \sim N(0, \sigma_\varepsilon^2)\\
\mu_{t+1} &= \mu_t + \delta_t + w_t, \quad w_t \sim N(0, \sigma_w^2) \\
\delta_{t+1} &= \delta_t +  \zeta_t, \quad \zeta_t \sim N(0, \sigma_\zeta^2)
\end{aligned}
$$

$$
\begin{aligned}
y_t = (1, 0)
\begin{pmatrix}
\mu_t\\
\delta_t
\end{pmatrix}
+ \varepsilon_t, \quad \varepsilon_t \sim N(0, \sigma_\varepsilon^2)\\

\begin{pmatrix}
\mu_{t+1}\\
\delta_{t+1}
\end{pmatrix}
=
\begin{pmatrix}
1 & 1\\
0 & 1
\end{pmatrix}
\begin{pmatrix}
\mu_{t}\\
\delta_{t}
\end{pmatrix}
+ 
\begin{pmatrix}
1 & 0\\
0 & 1
\end{pmatrix}
\begin{pmatrix}
w_t\\
\zeta_t
\end{pmatrix}
\\

\begin{pmatrix}
w_t\\
\zeta_t
\end{pmatrix}
\sim N\left(
\begin{pmatrix}
0\\
0
\end{pmatrix},
\begin{pmatrix}
\sigma_w^2 & 0\\
0 & \sigma_\zeta^2
\end{pmatrix}
\right)
\end{aligned}
$$

## モデリング

```{r}
model_lt <- SSModel(y ~ SSMtrend(degree = 2, Q = c(list(NA), list(NA))),
                 data=data, H=NA)

fit_lt <- fitSSM(model_lt, numeric(3), method="BFGS")
```

### モデルパラメータ

$$
\boldsymbol{Z} = (1,0)
$$

```{r}
model_lt$Z
```

$$
\boldsymbol{T} =
\begin{pmatrix}
1 & 1\\
0 & 1
\end{pmatrix}
$$


```{r}
model_lt$T
```

$$
\boldsymbol{R} = \begin{pmatrix}
1 & 0\\
0 & 1
\end{pmatrix}
$$


```{r}
model_lt$R
```


### 推定パラメータ

$$
\boldsymbol{H}=\sigma_\varepsilon^2
$$

```{r}
fit_lt$model$H
```


$$
\boldsymbol{Q} = 
\begin{pmatrix}
\sigma_w^2 & 0\\
0 & \sigma_\zeta^2
\end{pmatrix}
$$
```{r}
fit_lt$model$Q
```

## 結果

### 全成分

$$
P(y_t \vert y_{1:T})
$$

```{r}
data_all_lt <- makeDataFrameQuantile(fitted_model = fit_lt$model, data=data, states = "all", interval = "prediction", n_ahead=10) %>%
  left_join(data, by="day")

p <- ggplot(data_all_lt) +
  geom_vline(xintercept = max(data$day), linetype="dotted")+
  geom_line(aes(x=day, y=y), color="black") + 
  geom_line(aes(x=day, y=pred), color="blue", linetype="dashed") + 
  geom_ribbon(aes(x = day, ymin = lwr, ymax = upr),
            fill = "blue", alpha = 0.5)
print(p)
```

### トレンド成分

$$
  P(\mu_t \vert y_{1:T})
$$

```{r}
data_trend_lt <- makeDataFrameQuantile(fitted_model = fit_lt$model,
                                     data=data,
                                     states = "trend",
                                     interval = "confidence",
                                     n_ahead=10
                                     ) %>%
  left_join(data, by="day")

p <- ggplot(data_trend_lt) +
  geom_vline(xintercept = max(data$day), linetype="dotted")+
  geom_line(aes(x=day, y=pred), color="blue", linetype="dashed") + 
  geom_ribbon(aes(x = day, ymin = lwr, ymax = upr),
            fill = "blue", alpha = 0.5)
print(p)
```

### 傾き成分

$$
  P(\delta_t \vert y_{1:T})
$$

```{r}
data_slope_lt <- makeDataFrameQuantile(fitted_model = fit_lt$model,
                                     data=data,
                                     states = "slope",
                                     interval = "confidence",
                                     n_ahead=10
                                     ) %>%
  left_join(data, by="day")

p <- ggplot(data_slope_lt) +
  geom_vline(xintercept = max(data$day), linetype="dotted")+
  geom_line(aes(x=day, y=pred), color="blue", linetype="dashed") + 
  geom_ribbon(aes(x = day, ymin = lwr, ymax = upr),
            fill = "blue", alpha = 0.5)
print(p)
```


# 季節成分 + ローカルレベルモデル

$$
\begin{aligned}
y_t &= \mu_t + \gamma_t + \varepsilon_t, \quad \varepsilon_t \sim N(0, \sigma_\varepsilon^2)\\
\mu_{t+1} &= \mu_t + \eta^{(\mu)}_t, \quad \eta^{(\mu)}_t \sim N(0, \sigma_\mu^2) \\
\gamma_{t+1} &= -\sum_{i=0}^{s-2} \gamma_{t-i} +  \eta^{(\gamma)}_t, \quad \eta^{(\gamma)}_t \sim N(0, \sigma_\gamma^2)
\end{aligned}
$$

$$
\begin{aligned}
y_t = (1, 1, 0, 0, \cdots, 0)
\begin{pmatrix}
\mu_{t}\\
\gamma_{t}\\
\gamma_{t-1}\\
\gamma_{t-2}\\
\vdots\\
\gamma_{t-s+2}
\end{pmatrix}
+ \varepsilon_t, \quad \varepsilon_t \sim N(0, \sigma_\varepsilon^2)\\

\begin{pmatrix}
\mu_{t+1}\\
\gamma_{t+1}\\
\gamma_t\\
\gamma_{t-1}\\
\vdots\\
\gamma_{t-s+3}
\end{pmatrix}
=
\begin{pmatrix}
1 & 0 & 0 & 0 & \cdots & 0 & 0\\
0 & -1 & -1 & -1 & \cdots & -1 & -1\\
0 & 1 & 0 & 0 &\cdots & 0 & 0\\
0 & 0 & 1 & 0 &\cdots & 0 &0\\
\vdots & \vdots & \vdots & \cdots & \vdots & \vdots\\
0 & 0 & 0 & 0 &\cdots & 1 & 0\\
\end{pmatrix}
\begin{pmatrix}
\mu_{t}\\
\gamma_{t}\\
\gamma_{t-1}\\
\gamma_{t-2}\\
\vdots\\
\gamma_{t-s+2}
\end{pmatrix}
+ 
\begin{pmatrix}
1 & 0\\
0 & 1\\
0 & 0\\
0 & 0\\
\vdots & \vdots\\
0 & 0
\end{pmatrix}
\begin{pmatrix}
\eta^{(\mu)}_t\\
\eta^{(\gamma)}_t
\end{pmatrix}
\\

\begin{pmatrix}
\eta^{(\mu)}_t\\
\eta^{(\gamma)}_t
\end{pmatrix}
\sim N\left(
\begin{pmatrix}
0\\
0
\end{pmatrix},
\begin{pmatrix}
\sigma_\mu^2 & 0\\
0 & \sigma_\gamma^2
\end{pmatrix}
\right)
\end{aligned}
$$

## モデリング

```{r}
model_s_ll <- SSModel(y ~ SSMtrend(degree = 1, Q = NA)
                    + SSMseasonal(period=4, sea.type="dummy", Q=NA),
                 data=data, H=NA)

fit_s_ll <- fitSSM(model_s_ll, numeric(3), method="BFGS")
```

### モデルパラメータ

$$
\boldsymbol{Z} = (1,1,0, 0, ..., 0)
$$

```{r}
model_s_ll$Z
```

$$
\boldsymbol{T} =
\begin{pmatrix}
1 & 0 & 0 & 0 & \cdots & 0 & 0\\
0 & -1 & -1 & -1 & \cdots & -1 & -1\\
0 & 1 & 0 & 0 &\cdots & 0 & 0\\
0 & 0 & 1 & 0 &\cdots & 0 &0\\
\vdots & \vdots & \vdots & \cdots & \vdots & \vdots\\
0 & 0 & 0 & 0 &\cdots & 1 & 0\\
\end{pmatrix}
$$


```{r}
model_s_ll$T
```

$$
\boldsymbol{R} = \begin{pmatrix}
1 & 0\\
0 & 1\\
0 & 0\\
0 & 0\\
\vdots & \vdots\\
0 & 0
\end{pmatrix}
$$


```{r}
model_s_ll$R
```


### 推定パラメータ

$$
\boldsymbol{H}=\sigma_\varepsilon^2
$$

```{r}
fit_s_ll$model$H
```


$$
\boldsymbol{Q} = 
\begin{pmatrix}
\sigma_\mu^2 & 0\\
0 & \sigma_\gamma^2
\end{pmatrix}
$$

```{r}
fit_s_ll$model$Q
```

## 結果

### 全成分

$$
P(y_t \vert y_{1:T})
$$

```{r}
data_all_s_ll <- makeDataFrameQuantile(fitted_model = fit_s_ll$model, data=data, states = "all", interval = "prediction", n_ahead=10) %>%
  left_join(data, by="day")

p <- ggplot(data_all_s_ll) +
  geom_vline(xintercept = max(data$day), linetype="dotted")+
  geom_line(aes(x=day, y=y), color="black") + 
  geom_line(aes(x=day, y=pred), color="blue", linetype="dashed") + 
  geom_ribbon(aes(x = day, ymin = lwr, ymax = upr),
            fill = "blue", alpha = 0.5)
print(p)
```

### トレンド成分

$$
  P(\mu_t \vert y_{1:T})
$$

```{r}
data_trend_s_ll <- makeDataFrameQuantile(fitted_model = fit_s_ll$model,
                                     data=data,
                                     states = "trend",
                                     interval = "confidence",
                                     n_ahead=10
                                     ) %>%
  left_join(data, by="day")

p <- ggplot(data_trend_s_ll) +
  geom_vline(xintercept = max(data$day), linetype="dotted")+
  geom_line(aes(x=day, y=pred), color="blue", linetype="dashed") + 
  geom_ribbon(aes(x = day, ymin = lwr, ymax = upr),
            fill = "blue", alpha = 0.5)
print(p)
```

### 季節成分

$$
  P(\gamma_t \vert y_{1:T})
$$

```{r}
data_seasonal_s_ll <- makeDataFrameQuantile(fitted_model = fit_s_ll$model,
                                     data=data,
                                     states = "seasonal",
                                     interval = "confidence",
                                     n_ahead=10
                                     ) %>%
  left_join(data, by="day")

p <- ggplot(data_seasonal_s_ll) +
  geom_vline(xintercept = max(data$day), linetype="dotted")+
  geom_line(aes(x=day, y=pred), color="blue", linetype="dashed") + 
  geom_ribbon(aes(x = day, ymin = lwr, ymax = upr),
            fill = "blue", alpha = 0.5)
print(p)
```
